declare module "camelize";
declare module "dasherize";
declare module "heroku-ssl-redirect";
declare module "isomorphic-style-loader/lib/withStyles";
declare module "react-collapse";
declare module "react-helmet";
declare module "react-instantsearch/connectors";
declare module "react-instantsearch/dom";
declare module "react-stickynode";
